config/routes.rb
Rails.application.routes.draw do
  get 'pages/event'

  get 'pages/rsoc'

  get 'pages/rubyconf'

  get 'pages/contact'

  get 'pages/about'

  root 'pages#home'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def event
  end

  def rsoc
  end

  def rubyconf
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :professional, :email_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsGirls</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <nav>
      <ul>
          <li><%= link_to "Home" , root_path %></li>
        <li><%= link_to "Events" , pages_event_path %></li>
          <li><%= link_to "RSOC" , pages_rsoc_path %></li>
            <li><%= link_to "Rubyconf" , pages_rubyconf_path %></li>
            <li><%= link_to "About" , pages_about_path %></li>
            <li><%= link_to "contact" , pages_contact_path %></li>
              <li><%= link_to "registration" , new_user_path %></li>







      </ul>
      <div id="clear">
      </div>
    </nav>
    <%= yield %>

      </body>
</html>

app/views/pages/about.html.erb
<%= image_tag "together.jpg", width: "390", height: "355"%>
Together We build more Achieve more ..


<h1> Ashish Wadekar </h1>
 <h3>  He is passionate about Ruby </h3>



   <h1> Prithviraj sukale</h1>
   <h3> Working at Big binary </h3>

app/views/pages/contact.html.erb
<p> We are happy to help You ..</p>
You want to become
Rails  STUDENT AMBASSADOR PROGRAM  !!!!!!!!!!!!!!!!!!!!!
<h1>
We have currently happy to announce  accepting applications for the Campus Ambassador Program.
</h1> Please check back in at a later date.


  <%= link_to "Register here " , new_user_path, class: "btn btn-lg btn-success" %>

app/views/pages/event.html.erb
<P>
   <h1> Rails Girls Pune </h1>
21st January 2018
Namaskar world!
<h3>
Rails Girls comes to Pune on Sunday, January 21st!
<br>
During the one day workshop for women, we'll dive into the magical world of Ruby on Rails. This event is for beginner women who want to learn more about coding and building things.</h3>

Follow @RailsGirlsPune on Twitter for the latest updates!
<br>


You can also check out our facebook page here

Registrations Closed!


You learn designing, prototyping and coding with the help from our coaches.

<%= image_tag "railsfb_2.jpg", width: "690", height: "355"%>

app/views/pages/home.html.erb
<div class="container light">
  <div class="wrapper">
    <div id="logo_left">
      <%= image_tag "railgirl_img.png", width: "590", height: "105"%>
    </div>
    <div id="logo_right">
      <form>
        <input id ="textstyle" type="text" name="textbox"/>
        <input  id ="button" type="button" name="search" value="search"/>
      </form>
    </div>
    <div id="clear">
    </div>
</div>
</div>

<%= image_tag "railsfb_1.jpg", width: "690", height: "355"%>
<!--
<div class="container medium">
  <div class="wrapper">
    MENU
  </div>
</div>-->

app/views/pages/rsoc.html.erb
  <%= image_tag "rgsoc_logo.png", width: "590", height: "335"%>
  Coming Soon Register here ....
  <h1>
  last Date of Registrations 24 jan 2018 </h1>
  <a href="https://railsgirlssummerofcode.org/">RGSOC Registrations</a>

app/views/pages/rubyconf.html.erb
<p>
  <h1> ABOUT RUBYCONF INDIA </h1>
  <h2>
RubyConf India is a global event complementing other RubyConf events across the world.</h2>


This year our event is a 2 day, single track event focused on Ruby Language, Framework and Tools.
Note: The conference is entirely in English.</p>

<%= image_tag "ruby_conf_logo.svg", width: "690", height: "355"%>
<h1>
  FAQ </h1>


  <h4>
    Q. I had purchased a conference ticket but now my plan has changed. Will you refund my money?
  </h4>
  <h5>
We had mentioned at the time of buying the ticket, that it is non-refundable. <br>
However, we will try and help you find buyers for your ticket. Once you sell your ticket
<br> do inform us the purchaser's name so that we can print the attendee badge in his/her name.
<h5>
  

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :user_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :user_last_name %>
  </div>

  <div class="field">
    <%= form.label :professional %>
    <%= form.text_field :professional, id: :user_professional %>
  </div>

  <div class="field">
    <%= form.label :email_id %>
    <%= form.text_field :email_id, id: :user_email_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Professional</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.professional %></td>
        <td><%= user.email_id %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Professional:</strong>
  <%= @user.professional %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email_id %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>